.TH wm 1 "September 2025" "2.3" "User Commands"
.SH NAME
wm - shows animation of war machine.
.SH SYNOPSIS
.B wm
.B [ -KLBFIPMbde ]
.SH DESCRIPTION
The command \fBwm\fR shows ASCII art of war machine in the terminal.
By default, it displays the Tiger II from Germany.
.SH OPTIONS
.TP
.B -K
Shows the KV-2 from USSR.
.TP
.B -L
Shows the french Leclerc MBT.
.TP
.B -B
Shows the BM-13 (Katyusha) from USSR.
.TP
.B -F
Shows the Renault FT-17 from France.
.TP
.B -I
Shows the IS-2 from USSR.
.TP
.B -P
Shows the Pz. IV ausf. H from Germany.
.TP
.B -M
Shows the Maus from Germany.
.TP
.B -b
Blitzkrieg, the tank / vehicle goes faster.
.TP
.B -d
Disco mode. Alternate color during animation.
.TP
.B -e
Escape. Allows interupt by ctrl-c and stop by ctrl-z.
.SH AUTHOR 
Written by Abel GOMES <abel.gomes@etu.unistra.fr>
.PP
Inspired by the command \fBsl\fR written by Toyoda Masashi (mtoyoda@acm.org)
.SH SEE ALSO
sl(1)