.TH wm 1 "September 2025" "2.0" "User Commands"
.SH NAME
wm - shows animation of war machine
.SH SYNOPSIS
.B wm
.RI [ options ]
.SH DESCRIPTION
The command \fBwm\fR shows ASCII art of war machine in the terminal.
By default, it displays the Tiger II tank.
.SH OPTIONS
.TP
.B -K
Shows the KV-2 tank from USSR.
.TP
.B -b
Blitzkrieg, the tank goes faster.
.TP
.B -d
Disco mode. Alternate color during animation.
.TP
.B -e
Escape. Allows interupt by ctrl-c and stop by ctrl-z.
.SH AUTHOR 
Written by Abel GOMES <abel.gomes@etu.unistra.fr>
.PP
Inspired by the command \fBsl\fR written by Toyoda Masashi (mtoyoda@acm.org)
.SH SEE ALSO
sl(1)